name: Publish Docker Image

# Trigger the workflow on push or tag
on:
  push:
    branches:
      - main  # Build the image when there is a push on the main branch
    tags:
      - 'v*'  # Build the image when a version tag is pushed (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Log in to GitHub Container Registry (GHCR)
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build the Docker image
    - name: Build the Docker image
      run: |
        # Get the tag name or use 'latest' if it's a push to the main branch
        TAG=${GITHUB_REF#refs/tags/}
        if [ "${{ github.ref_type }}" == "branch" ]; then
          TAG=latest
        fi
        docker build . -t ghcr.io/${{ github.repository }}:$TAG

    # Push the Docker image to GHCR
    - name: Push Docker image to GHCR
      run: |
        # Push the tag and also update the 'latest' tag for versioned tags
        TAG=${GITHUB_REF#refs/tags/}
        if [ "${{ github.ref_type }}" == "branch" ]; then
          TAG=latest
        fi
        docker push ghcr.io/${{ github.repository }}:$TAG

        # If a version tag, also push the image as 'latest'
        if [ "${{ github.ref_type }}" == "tag" ]; then
          docker tag ghcr.io/${{ github.repository }}:$TAG ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest
        fi